--e
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Entity spawner V0.1")

-- MAIN SPAWNING
local Main = Window:NewTab("Custom Entity Spawner")
local Main2 = Window:NewTab("Entity Spawner")
local Main3 = Window:NewTab("Items")

Main:NewButton("Greg", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Greg%20Raw.lua"))()
  end)
Main:NewButton("A-25 From Rooms but Doors", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Custom%20Entities/A-25%20Rooms%20but%20doors.lua"))()
  end)
Main:NewButton("A-35 Form IR", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Custom%20Entities/A-35.lua"))()
  end)
Main:NewButton("Trollace", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Custom%20Entities/TrollFace.lua"))()
  end)
Main:NewButton("Trollace", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Custom%20Entities/TrollFace.lua"))()
  end)
Main:NewButton("Rebound", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Rebound%20Raw.lua"))()
  end)
Main:NewButton("Depth", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Depth%20Raw.lua"))()
  end)
Main:NewButton("A-60", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/A-60%20Raw.lua"))()
  end)
Main2:NewButton("Rush", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Utilities/refs/heads/main/Doors/Entity%20Spawner/V2/Source.lua"))()
  end)
Main2:NewButton("Blitz", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Utilities/refs/heads/main/Doors/Entity%20Spawner/V2/Example_Blitz.lua"))()
  end)
Main3:NewButton("Crucfix", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Utilities/refs/heads/main/Doors/Entity%20Spawner/Crucifix.lua"))()
  end)
