--e
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Entity spawner V0.1")

-- MAIN SPAWNING
local Main = Window:NewTab("Custom Entity Spawner")
local MainSection = Main:NewSection("Custom")
local Main2 = Window:NewTab("Entity Spawner")
local Main2Section = Main2:NewSection("Basic")
local Main3 = Window:NewTab("Items")
local Main3Section = Main3:NewSection("Giver")

MainSection:NewButton("Greg", "Spawning", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Greg%20Raw.lua"))()
  end)
MainSection:NewButton("A-25 From Rooms but Doors", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Custom%20Entities/A-25%20Rooms%20but%20doors.lua"))()
  end)
MainSection:NewButton("A-35 From IR", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Custom%20Entities/A-35.lua"))()
  end)
MainSection:NewButton("Trollace", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Custom%20Entities/TrollFace.lua"))()
  end)
MainSection:NewButton("Rebound", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Rebound%20Raw.lua"))()
  end)
MainSection:NewButton("Depth", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Depth%20Raw.lua"))()
  end)
MainSection:NewButton("A-60", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/A-60%20Raw.lua"))()
  end)
Main2Section:NewButton("Rush", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Utilities/refs/heads/main/Doors/Entity%20Spawner/V2/Source.lua"))()
  end)
Main2Section:NewButton("Ambush", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/Timofey2339/Depth-doors-model/refs/heads/main/Entities/Ambush.lua"))()
  end)
Main2Section:NewButton("Blitz", "Spawning", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Utilities/refs/heads/main/Doors/Entity%20Spawner/V2/Example_Blitz.lua"))()
  end)
Main3Section:NewButton("Crucfix", "Giving", function()
   	loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Utilities/refs/heads/main/Doors/Entity%20Spawner/Crucifix.lua"))()
  end)
