require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Particulate Mode v1.9 has been Loaded! ",true)
wait(2) require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("made by Timofey2339",true)
wait(2) require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("thanks opaer9898 for testing",true)
wait(2) require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("big thanks to Jabiss#1517 for dread idea",true)
wait(2) require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Enjoy the scritpt!",true)
